version: 0.0
os: linux

files:
  
source:  /
  destination: /home/ubuntu/front
  overwrite: yes

permissions:
  - object: /home/ubuntu/front
    owner: ubuntu
    group: ubuntu
    mode: 755
  
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
